# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, verbose_name='设备部位')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('method', models.CharField(max_length=50, verbose_name='检查方式')),
                ('target', models.TextField(max_length=100, verbose_name='点检标准')),
                ('type', models.CharField(max_length=50, verbose_name='领域')),
                ('period', models.PositiveIntegerField(choices=[(0, '每日'), (1, '１个月'), (2, '３个月'), (3, '６个月'), (4, '１年'), (5, '３年')], default=0, verbose_name='周期')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('next_time', models.DateTimeField(verbose_name='下次时间')),
                ('guide', models.FileField(upload_to='', verbose_name='指导书')),
                ('result', models.CharField(max_length=50, verbose_name='结果')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='设备名称')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '点检保养',
                'verbose_name_plural': '点检保养',
            },
        ),
    ]
