# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_maintenance_next_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='start_time',
            field=models.DateField(verbose_name='开始时间'),
        ),
    ]
