# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Malfunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='故障内容')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('stop_time', models.DateTimeField(verbose_name='故障时间')),
                ('method', models.TextField(max_length=100, verbose_name='处理方法')),
                ('duty', models.PositiveIntegerField(choices=[(0, '1S'), (1, '2S')], default=0, verbose_name='勤务')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='设备名称')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '故障履历',
                'verbose_name_plural': '故障履历',
            },
        ),
    ]
