# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malfunction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunction',
            name='stop_time',
            field=models.TimeField(verbose_name='故障时间'),
        ),
    ]
