# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malfunction', '0002_auto_20190513_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunction',
            name='stop_time',
            field=models.CharField(max_length=10, verbose_name='故障时间'),
        ),
    ]
