# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='备件名称')),
                ('model', models.CharField(max_length=50, verbose_name='备件型号')),
                ('type', models.CharField(max_length=50, verbose_name='备件规格')),
                ('quantity', models.IntegerField(verbose_name='备件数量')),
                ('price', models.FloatField(verbose_name='备件价格')),
                ('position', models.CharField(max_length=50, verbose_name='备件位置')),
                ('equip', models.ManyToManyField(to='equipment.Equipment', verbose_name='设备名称')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='采购人')),
            ],
            options={
                'verbose_name': '备件管理',
                'verbose_name_plural': '备件管理',
            },
        ),
    ]
