# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('accessory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='equip',
        ),
        migrations.AddField(
            model_name='accessory',
            name='equip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='设备名称'),
            preserve_default=False,
        ),
    ]
