# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessory', '0002_auto_20190514_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='备件价格'),
        ),
    ]
